using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;

namespace Niddy.Avalonia.PageSystem;

/// <summary>
///     Registers a set of pages with the <see cref="PageRegistry"/>. The <c>Niddy.Avalonia.Generators</c>
///     package generates one per assembly; you don't normally implement this yourself.
/// </summary>
public interface IPageProvider
{
    /// <summary>Registers the provider's pages.</summary>
    void RegisterPages();
}

/// <summary>
///     Marks the <see cref="IPageProvider"/> of an assembly, so the <see cref="PageRegistry"/> finds its pages
///     when the assembly is loaded. Generated by the <c>Niddy.Avalonia.Generators</c> package.
/// </summary>
/// <param name="providerType">The provider class, which must have a public parameterless constructor.</param>
[AttributeUsage(AttributeTargets.Assembly)]
[EditorBrowsable(EditorBrowsableState.Never)]
public sealed class PageProviderAttribute(
    [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] Type providerType
) : Attribute
{
    /// <summary>The provider class.</summary>
    [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)]
    public Type ProviderType { get; } = providerType;
}
